# Generated by Django 5.1.7 on 2025-03-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_category_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category_choices',
            field=models.CharField(choices=[('MEN', 'Men'), ('WOMEN', 'Women'), ('KIDS', 'Kids'), ('ACCESSORIES', 'Accessories')], default='shirt', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(default='shirt', max_length=20),
        ),
    ]
